-- 这里是定义数据结构的SQL，每次运行都会执行，此文件不能为空，必须至少写一句Sql语句。
drop table user if exists
create table user (id bigint generated by default as identity, avatar varchar(200), email varchar(50) not null, name varchar(20) not null, password varchar(100) not null, username varchar(20) not null, primary key (id))
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)